apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  type: NodePort
  selector:
    app: credit-nation
    service: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001