apiVersion: v1
kind: Service
metadata:
  name: loan-service-svc
spec:
  type: NodePort
  selector:
    app: credit-nation
    service: loan-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80