apiVersion: v1
kind: Service
metadata:
  name: user-registration-svc
spec:
  type: NodePort
  selector:
    app: credit-nation
    service: user-registration
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000